### ISSUE TITLE
Volunteering for Documentation help.

### ISSUE THREAD

**Issue by AnmolTomer** [siddhantkushwaha/todd#1]
Hi, @siddhantkushwaha I came across this project of yours while browsing GitHub. I would like to volunteer for documentation help . If that's fine by you, let me know.

**Comment by siddhantkushwaha** [comment]
Hey @AnmolTomer, yeah yeah sure. Let me know how I can get in touch with you to discuss.

**Comment by AnmolTomer** [comment]
You can contact me on Telegram using this link: https://t.me/toxicrick or email me anmol3540@gmail.com, whichever you prefer.
